<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <NoWarn>$(NoWarn);xUnit1051;CA1711</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="*.cs" />
    <Compile Remove="2026-03-26\**\*.cs" />
    <Compile Remove="2026-12-01\**\*.cs" />
    <Compile Remove="TestWebApplicationFixture\**\*.cs" />
    <ProjectReference Include="..\src\Api.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MartinCostello.Logging.XUnit.v3" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Trellis.Testing.AspNetCore" />
  </ItemGroup>
</Project>
